apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-gpu
  namespace: ml-training
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: trainer
          image: zanjum11/mlops-train:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
            - name: data-volume
              mountPath: /app/data
            - name: checkpoints-volume
              mountPath: /app/checkpoints
      volumes:
        - name: config-volume
          configMap:
            name: training-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: checkpoints-volume
          persistentVolumeClaim:
            claimName: checkpoints-pvc
      restartPolicy: Never
  backoffLimit: 2